// Mapeamento de nome de time (como retornado pela API-Football, em inglês
// para seleções) → português. Cobre as seleções da Copa do Mundo 2026 e
// clubes recorrentes na Libertadores/Sul-Americana/Série B. Times sem
// entrada aqui mantêm o nome original (ver translateTeamName).
const TEAM_NAME_PT: Record<string, string> = {
  // Copa do Mundo 2026 — seleções
  england: "Inglaterra",
  germany: "Alemanha",
  france: "França",
  spain: "Espanha",
  croatia: "Croácia",
  netherlands: "Holanda",
  belgium: "Bélgica",
  switzerland: "Suíça",
  denmark: "Dinamarca",
  sweden: "Suécia",
  norway: "Noruega",
  poland: "Polônia",
  serbia: "Sérvia",
  ukraine: "Ucrânia",
  romania: "Romênia",
  hungary: "Hungria",
  slovakia: "Eslováquia",
  "czech republic": "Rep. Tcheca",
  turkey: "Turquia",
  scotland: "Escócia",
  wales: "País de Gales",
  austria: "Áustria",
  ghana: "Gana",
  senegal: "Senegal",
  morocco: "Marrocos",
  nigeria: "Nigéria",
  cameroon: "Camarões",
  "dr congo": "Rep. Congo",
  mali: "Mali",
  "ivory coast": "Costa do Marfim",
  "south africa": "África do Sul",
  japan: "Japão",
  "south korea": "Coreia do Sul",
  iran: "Irã",
  "saudi arabia": "Arábia Saudita",
  qatar: "Catar",
  australia: "Austrália",
  "new zealand": "Nova Zelândia",
  usa: "Estados Unidos",
  "united states": "Estados Unidos",
  mexico: "México",
  canada: "Canadá",
  honduras: "Honduras",
  panama: "Panamá",
  "costa rica": "Costa Rica",
  jamaica: "Jamaica",
  venezuela: "Venezuela",
  bolivia: "Bolívia",
  paraguay: "Paraguai",
  chile: "Chile",
  peru: "Peru",
  ecuador: "Equador",
  colombia: "Colômbia",
  uruguay: "Uruguai",
  argentina: "Argentina",
  brazil: "Brasil",
  jordan: "Jordânia",
};

export function translateTeamName(name: string): string {
  return TEAM_NAME_PT[name.trim().toLowerCase()] ?? name;
}
