// Mapeamento de nome de seleção (inglês/português) → código ISO usado pelo
// flagcdn.com, cobrindo as 48 seleções da Copa do Mundo 2026.
const TEAM_FLAG_CODES: Record<string, string> = {
  portugal: "pt",
  england: "gb",
  brazil: "br",
  brasil: "br",
  france: "fr",
  germany: "de",
  spain: "es",
  argentina: "ar",
  austria: "at",
  croatia: "hr",
  ghana: "gh",
  panama: "pa",
  "dr congo": "cd",
  jordan: "jo",
  usa: "us",
  "united states": "us",
  mexico: "mx",
  canada: "ca",
  morocco: "ma",
  senegal: "sn",
  japan: "jp",
  "south korea": "kr",
  australia: "au",
  netherlands: "nl",
  belgium: "be",
  switzerland: "ch",
  uruguay: "uy",
  colombia: "co",
  ecuador: "ec",
  chile: "cl",
  peru: "pe",
  nigeria: "ng",
  cameroon: "cm",
  "ivory coast": "ci",
  mali: "ml",
  "saudi arabia": "sa",
  iran: "ir",
  qatar: "qa",
  serbia: "rs",
  poland: "pl",
  hungary: "hu",
  "czech republic": "cz",
  slovakia: "sk",
  turkey: "tr",
  romania: "ro",
  ukraine: "ua",
  denmark: "dk",
  sweden: "se",
  norway: "no",
  finland: "fi",
  scotland: "gb-sct",
  wales: "gb-wls",
  "new zealand": "nz",
  honduras: "hn",
  "costa rica": "cr",
  guatemala: "gt",
  jamaica: "jm",
  venezuela: "ve",
  bolivia: "bo",
  paraguay: "py",
};

export function getFlagUrl(teamName: string): string | null {
  const code = TEAM_FLAG_CODES[teamName.trim().toLowerCase()];
  return code ? `https://flagcdn.com/w80/${code}.png` : null;
}
